name: em_cartaz
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_modular: ^4.4.0
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  google_fonts: ^2.2.0
  lottie: ^1.2.1
  shared_preferences: ^2.0.12
  motion_toast: ^2.1.1
  sqflite: ^2.0.2
  path: ^1.8.0
  dio: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0
  mobx_codegen: ^2.0.5+2
  modular_test: ^1.0.1+1
  build_runner: ^2.1.7



flutter:
  uses-material-design: true

  assets:
    - assets/

  